import ICharacter from '@modules/characters/entities/ICharacter';

// Character data based on mcu_characters.json
const characters: ICharacter[] = [
  {
    id: 1,
    name: 'Tony Stark',
    alias: 'Iron Man',
    description: 'Genius billionaire playboy philanthropist who created the Iron Man suit.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 1, // Iron Man
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 2,
    name: 'Steve Rogers',
    alias: 'Captain America',
    description: 'Super soldier from World War II who represents the best of American values.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 5, // Captain America: The First Avenger
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 3,
    name: 'Thor Odinson',
    alias: 'Thor',
    description: 'God of Thunder from Asgard, wielder of Mjolnir.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 4, // Thor
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 4,
    name: 'Bruce Banner',
    alias: 'Hulk',
    description: 'Scientist who transforms into the Hulk when angry.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 2, // The Incredible Hulk
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 5,
    name: 'Natasha Romanoff',
    alias: 'Black Widow',
    description: 'Former Russian spy and master assassin turned Avenger.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 3, // Iron Man 2
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 6,
    name: 'Clint Barton',
    alias: 'Hawkeye',
    description: 'Master archer and former S.H.I.E.L.D. agent.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 4, // Thor (cameo)
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 7,
    name: 'Nick Fury',
    alias: undefined,
    description: 'Director of S.H.I.E.L.D. and master strategist.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 1, // Iron Man (post-credits)
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 8,
    name: 'James Rhodes',
    alias: 'War Machine',
    description: 'Tony Stark\'s best friend and military liaison.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 1, // Iron Man
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 9,
    name: 'Pepper Potts',
    alias: undefined,
    description: 'CEO of Stark Industries and Tony Stark\'s love interest.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 1, // Iron Man
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 10,
    name: 'Happy Hogan',
    alias: undefined,
    description: 'Tony Stark\'s bodyguard and head of security.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 1, // Iron Man
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 11,
    name: 'Phil Coulson',
    alias: undefined,
    description: 'S.H.I.E.L.D. agent and fan of Captain America.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 1, // Iron Man
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 12,
    name: 'Maria Hill',
    alias: undefined,
    description: 'Deputy Director of S.H.I.E.L.D. and Nick Fury\'s right hand.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 6, // The Avengers
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 13,
    name: 'Peter Parker',
    alias: 'Spider-Man',
    description: 'Teenage superhero with spider-like abilities.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 8, // Captain America: Civil War
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 14,
    name: 'Peter Parker',
    alias: 'Spider-Man',
    description: 'Spider-Man from the Sam Raimi universe.',
    image_url: undefined,
    continuity: 'Sony Spider-Man Universe',
    multiverse_designation: 'Earth-96283',
    variant_of: 13, // Variant of MCU Peter Parker
    first_appearance_movie_id: undefined,
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 15,
    name: 'Peter Parker',
    alias: 'Spider-Man',
    description: 'Spider-Man from The Amazing Spider-Man universe.',
    image_url: undefined,
    continuity: 'Sony Spider-Man Universe',
    multiverse_designation: 'Earth-120703',
    variant_of: 13, // Variant of MCU Peter Parker
    first_appearance_movie_id: undefined,
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 16,
    name: 'Michelle Jones',
    alias: 'MJ',
    description: 'Peter Parker\'s love interest and classmate.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 9, // Spider-Man: Homecoming
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 17,
    name: 'Ned Leeds',
    alias: undefined,
    description: 'Peter Parker\'s best friend and "guy in the chair".',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 9, // Spider-Man: Homecoming
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 18,
    name: 'Norman Osborn',
    alias: 'Green Goblin',
    description: 'Spider-Man\'s arch-nemesis from the Sam Raimi universe.',
    image_url: undefined,
    continuity: 'Sony Spider-Man Universe',
    multiverse_designation: 'Earth-96283',
    variant_of: undefined,
    first_appearance_movie_id: undefined,
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 19,
    name: 'Otto Octavius',
    alias: 'Doctor Octopus',
    description: 'Scientist turned villain from the Sam Raimi universe.',
    image_url: undefined,
    continuity: 'Sony Spider-Man Universe',
    multiverse_designation: 'Earth-96283',
    variant_of: undefined,
    first_appearance_movie_id: undefined,
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 20,
    name: 'Max Dillon',
    alias: 'Electro',
    description: 'Electrical engineer turned villain from The Amazing Spider-Man universe.',
    image_url: undefined,
    continuity: 'Sony Spider-Man Universe',
    multiverse_designation: 'Earth-120703',
    variant_of: undefined,
    first_appearance_movie_id: undefined,
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 21,
    name: 'Curt Connors',
    alias: 'The Lizard',
    description: 'Scientist who transforms into a lizard-like creature.',
    image_url: undefined,
    continuity: 'Sony Spider-Man Universe',
    multiverse_designation: 'Earth-120703',
    variant_of: undefined,
    first_appearance_movie_id: undefined,
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 22,
    name: 'Flint Marko',
    alias: 'Sandman',
    description: 'Criminal who gains sand-like powers.',
    image_url: undefined,
    continuity: 'Sony Spider-Man Universe',
    multiverse_designation: 'Earth-96283',
    variant_of: undefined,
    first_appearance_movie_id: undefined,
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 23,
    name: 'Quentin Beck',
    alias: 'Mysterio',
    description: 'Former Stark Industries employee turned illusionist villain.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 11, // Spider-Man: Far From Home
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 24,
    name: 'Peter Quill',
    alias: 'Star-Lord',
    description: 'Leader of the Guardians of the Galaxy and half-human, half-Celestial.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 12, // Guardians of the Galaxy
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 25,
    name: 'Gamora',
    alias: 'Gamora',
    description: 'Daughter of Thanos and deadliest woman in the galaxy.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 12, // Guardians of the Galaxy
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 26,
    name: 'Drax',
    alias: 'Drax the Destroyer',
    description: 'Warrior seeking revenge against Thanos.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 12, // Guardians of the Galaxy
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 27,
    name: 'Rocket Raccoon',
    alias: 'Rocket',
    description: 'Genetically modified raccoon and master tactician.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 12, // Guardians of the Galaxy
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 28,
    name: 'Groot',
    alias: 'Groot',
    description: 'Tree-like being and member of the Guardians of the Galaxy.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 12, // Guardians of the Galaxy
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 29,
    name: 'Nebula',
    alias: 'Nebula',
    description: 'Daughter of Thanos and Gamora\'s adoptive sister.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 12, // Guardians of the Galaxy
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 30,
    name: 'Stephen Strange',
    alias: 'Doctor Strange',
    description: 'Former neurosurgeon turned Master of the Mystic Arts.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 13, // Doctor Strange
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 31,
    name: 'Wong',
    alias: undefined,
    description: 'Master of the Mystic Arts and librarian of Kamar-Taj.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 13, // Doctor Strange
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 32,
    name: 'Christine Palmer',
    alias: undefined,
    description: 'Doctor and Stephen Strange\'s former colleague.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 13, // Doctor Strange
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 33,
    name: 'Karl Mordo',
    alias: undefined,
    description: 'Master of the Mystic Arts and former ally of Doctor Strange.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 13, // Doctor Strange
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 34,
    name: 'America Chavez',
    alias: undefined,
    description: 'Teenager with the ability to travel between universes.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 16, // Doctor Strange in the Multiverse of Madness
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 35,
    name: 'T\'Challa',
    alias: 'Black Panther',
    description: 'King of Wakanda and protector of his people.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 8, // Captain America: Civil War
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 36,
    name: 'Shuri',
    alias: undefined,
    description: 'Princess of Wakanda and brilliant scientist.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 14, // Black Panther
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 37,
    name: 'Okoye',
    alias: undefined,
    description: 'General of the Dora Milaje and protector of Wakanda.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 14, // Black Panther
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 38,
    name: 'Erik Killmonger',
    alias: 'Killmonger',
    description: 'T\'Challa\'s cousin and challenger to the throne of Wakanda.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 14, // Black Panther
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 39,
    name: 'Carol Danvers',
    alias: 'Captain Marvel',
    description: 'Former Air Force pilot turned cosmic superhero.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 15, // Captain Marvel
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 40,
    name: 'Monica Rambeau',
    alias: 'Photon',
    description: 'Maria Rambeau\'s daughter and former S.W.O.R.D. agent.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 15, // Captain Marvel
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 41,
    name: 'Kamala Khan',
    alias: 'Ms. Marvel',
    description: 'Teenage superhero with polymorphic abilities.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: undefined,
    first_appearance_tvshow_id: 1, // Ms. Marvel
  },
  {
    id: 42,
    name: 'Scott Lang',
    alias: 'Ant-Man',
    description: 'Former thief who can shrink and communicate with ants.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 17, // Ant-Man
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 43,
    name: 'Hope van Dyne',
    alias: 'Wasp',
    description: 'Daughter of Hank Pym and Janet van Dyne.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 17, // Ant-Man
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 44,
    name: 'Hank Pym',
    alias: 'Ant-Man',
    description: 'Scientist who discovered the Pym Particle.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 17, // Ant-Man
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 45,
    name: 'Janet van Dyne',
    alias: 'Wasp',
    description: 'Original Wasp and wife of Hank Pym.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 18, // Ant-Man and the Wasp
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 46,
    name: 'Loki Laufeyson',
    alias: 'Loki',
    description: 'God of Mischief and Thor\'s adoptive brother.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 4, // Thor
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 47,
    name: 'Wanda Maximoff',
    alias: 'Scarlet Witch',
    description: 'Reality-warping witch and former Avenger.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 7, // Captain America: The Winter Soldier (post-credits)
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 48,
    name: 'Vision',
    alias: 'Vision',
    description: 'Android created by Ultron and powered by the Mind Stone.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 10, // Avengers: Age of Ultron
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 49,
    name: 'Agatha Harkness',
    alias: 'Agatha',
    description: 'Powerful witch and former resident of Westview.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: undefined,
    first_appearance_tvshow_id: 2, // WandaVision
  },
  {
    id: 50,
    name: 'Shang-Chi',
    alias: 'Shang-Chi',
    description: 'Master of martial arts and wielder of the Ten Rings.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 19, // Shang-Chi and the Legend of the Ten Rings
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 51,
    name: 'Katy Chen',
    alias: undefined,
    description: 'Shang-Chi\'s best friend and ally.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 19, // Shang-Chi and the Legend of the Ten Rings
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 52,
    name: 'Wenwu',
    alias: 'The Mandarin',
    description: 'Shang-Chi\'s father and leader of the Ten Rings organization.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 19, // Shang-Chi and the Legend of the Ten Rings
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 53,
    name: 'Sersi',
    alias: undefined,
    description: 'Eternal with the power to manipulate matter.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 20, // Eternals
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 54,
    name: 'Ikaris',
    alias: undefined,
    description: 'Eternal with the power of flight and energy projection.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 20, // Eternals
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 55,
    name: 'Thena',
    alias: undefined,
    description: 'Eternal warrior with enhanced combat abilities.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 20, // Eternals
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 56,
    name: 'Valkyrie',
    alias: 'Valkyrie',
    description: 'Former Valkyrie and current King of New Asgard.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 16, // Thor: Ragnarok
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 57,
    name: 'Korg',
    alias: undefined,
    description: 'Kronan warrior and ally of Thor.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 16, // Thor: Ragnarok
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 58,
    name: 'Hela',
    alias: 'Hela',
    description: 'Goddess of Death and Odin\'s firstborn.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 16, // Thor: Ragnarok
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 59,
    name: 'James Buchanan Barnes',
    alias: 'Bucky',
    description: 'Former Winter Soldier and Steve Rogers\' best friend.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 5, // Captain America: The First Avenger
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 60,
    name: 'Peggy Carter',
    alias: undefined,
    description: 'S.H.I.E.L.D. founder and Steve Rogers\' love interest.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 5, // Captain America: The First Avenger
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 61,
    name: 'Sam Wilson',
    alias: 'Falcon',
    description: 'Former Air Force pararescue and Steve Rogers\' ally.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 7, // Captain America: The Winter Soldier
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 62,
    name: 'Thanos',
    alias: 'Thanos',
    description: 'Mad Titan seeking to balance the universe.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 6, // The Avengers (post-credits)
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 63,
    name: 'Ultron',
    alias: 'Ultron',
    description: 'AI created by Tony Stark and Bruce Banner.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 10, // Avengers: Age of Ultron
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 64,
    name: 'Kang the Conqueror',
    alias: 'Kang',
    description: 'Time-traveling conqueror and variant of He Who Remains.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 21, // Ant-Man and the Wasp: Quantumania
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 65,
    name: 'Victor Von Doom',
    alias: 'Doctor Doom',
    description: 'Ruler of Latveria and Reed Richards\' arch-nemesis.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: undefined, // Future movie
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 66,
    name: 'Emil Blonsky',
    alias: 'Abomination',
    description: 'Former soldier transformed into a gamma-powered monster.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 2, // The Incredible Hulk
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 67,
    name: 'Matt Murdock',
    alias: 'Daredevil',
    description: 'Blind lawyer by day, vigilante by night.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 12, // Spider-Man: No Way Home
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 68,
    name: 'Wilson Fisk',
    alias: 'Kingpin',
    description: 'Crime lord of New York City.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: undefined,
    first_appearance_tvshow_id: 3, // Daredevil
  },
  {
    id: 69,
    name: 'Jessica Jones',
    alias: 'Jessica Jones',
    description: 'Private investigator with superhuman strength.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: undefined,
    first_appearance_tvshow_id: 4, // Jessica Jones
  },
  {
    id: 70,
    name: 'Luke Cage',
    alias: 'Luke Cage',
    description: 'Hero for hire with unbreakable skin.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: undefined,
    first_appearance_tvshow_id: 5, // Luke Cage
  },
  {
    id: 71,
    name: 'Danny Rand',
    alias: 'Iron Fist',
    description: 'Living weapon and protector of K\'un-Lun.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: undefined,
    first_appearance_tvshow_id: 6, // Iron Fist
  },
  {
    id: 72,
    name: 'Frank Castle',
    alias: 'The Punisher',
    description: 'Vigilante seeking revenge for his family\'s murder.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: undefined,
    first_appearance_tvshow_id: 7, // The Punisher
  },
  {
    id: 73,
    name: 'Kate Bishop',
    alias: 'Hawkeye',
    description: 'Young archer and protégé of Clint Barton.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: undefined,
    first_appearance_tvshow_id: 8, // Hawkeye
  },
  {
    id: 74,
    name: 'Yelena Belova',
    alias: 'Black Widow',
    description: 'Natasha Romanoff\'s adoptive sister and fellow Black Widow.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 22, // Black Widow
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 75,
    name: 'Maya Lopez',
    alias: 'Echo',
    description: 'Deaf Native American warrior and former Kingpin associate.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: undefined,
    first_appearance_tvshow_id: 8, // Hawkeye
  },
  {
    id: 76,
    name: 'Jennifer Walters',
    alias: 'She-Hulk',
    description: 'Lawyer who gains Hulk-like powers.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: undefined,
    first_appearance_tvshow_id: 9, // She-Hulk: Attorney at Law
  },
  {
    id: 77,
    name: 'Marc Spector',
    alias: 'Moon Knight',
    description: 'Mercenary with dissociative identity disorder.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: undefined,
    first_appearance_tvshow_id: 10, // Moon Knight
  },
  {
    id: 78,
    name: 'Layla El-Faouly',
    alias: 'Scarlet Scarab',
    description: 'Archaeologist and wife of Marc Spector.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: undefined,
    first_appearance_tvshow_id: 10, // Moon Knight
  },
  {
    id: 79,
    name: 'Valentina Allegra de Fontaine',
    alias: 'Val',
    description: 'Mysterious government official recruiting anti-heroes.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 22, // Black Widow
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 80,
    name: 'Everett K. Ross',
    alias: undefined,
    description: 'CIA agent and ally of T\'Challa.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 8, // Captain America: Civil War
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 81,
    name: 'Talos',
    alias: undefined,
    description: 'Skrull general and ally of Carol Danvers.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: 15, // Captain Marvel
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 82,
    name: 'Blade',
    alias: 'Blade',
    description: 'Vampire hunter and Daywalker.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: undefined, // Future movie
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 83,
    name: 'Eddie Brock',
    alias: 'Venom',
    description: 'Investigative journalist bonded with an alien symbiote.',
    image_url: undefined,
    continuity: 'Sony Spider-Man Universe',
    multiverse_designation: 'Unknown',
    variant_of: undefined,
    first_appearance_movie_id: 12, // Spider-Man: No Way Home (cameo)
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 84,
    name: 'Wade Wilson',
    alias: 'Deadpool',
    description: 'Mercenary with healing factor and fourth-wall breaking abilities.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: undefined, // Future movie
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 85,
    name: 'Logan Howlett',
    alias: 'Wolverine',
    description: 'Mutant with healing factor and adamantium skeleton.',
    image_url: undefined,
    continuity: 'FOX X-Men Universe',
    multiverse_designation: 'Unknown',
    variant_of: undefined,
    first_appearance_movie_id: undefined, // Future movie
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 86,
    name: 'Laura',
    alias: 'X-23',
    description: 'Female clone of Wolverine with similar abilities.',
    image_url: undefined,
    continuity: 'FOX X-Men Universe',
    multiverse_designation: 'Unknown',
    variant_of: 85, // Variant of Wolverine
    first_appearance_movie_id: undefined, // Future movie
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 87,
    name: 'Cassandra Nova',
    alias: undefined,
    description: 'Charles Xavier\'s evil twin sister.',
    image_url: undefined,
    continuity: 'FOX X-Men Universe',
    multiverse_designation: 'Unknown',
    variant_of: undefined,
    first_appearance_movie_id: undefined, // Future movie
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 88,
    name: 'Reed Richards',
    alias: 'Mister Fantastic',
    description: 'Leader of the Fantastic Four with elastic powers.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: undefined, // Future movie
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 89,
    name: 'Sue Storm',
    alias: 'Invisible Woman',
    description: 'Member of the Fantastic Four with invisibility powers.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: undefined, // Future movie
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 90,
    name: 'Johnny Storm',
    alias: 'Human Torch',
    description: 'Member of the Fantastic Four with fire powers.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: undefined, // Future movie
    first_appearance_tvshow_id: undefined,
  },
  {
    id: 91,
    name: 'Ben Grimm',
    alias: 'The Thing',
    description: 'Member of the Fantastic Four with rock-like skin.',
    image_url: undefined,
    continuity: 'MCU',
    multiverse_designation: 'Earth-199999',
    variant_of: undefined,
    first_appearance_movie_id: undefined, // Future movie
    first_appearance_tvshow_id: undefined,
  },
];

export default characters; 